# Generated by Django 2.1.3 on 2018-11-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteFileModel',
            fields=[
                ('server_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('artist', models.CharField(default='', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('ID', models.CharField(default='', max_length=20)),
                ('song', models.FileField(null=True, upload_to='')),
            ],
            options={
                'ordering': ('server_id',),
            },
        ),
    ]
