# Generated by Django 2.1.3 on 2018-12-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoteFileModel',
            fields=[
                ('server_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('artist', models.CharField(default='', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('ID', models.CharField(default='', max_length=20)),
                ('song', models.FileField(null=True, upload_to='')),
            ],
            options={
                'ordering': ('server_id',),
            },
        ),
    ]
